// Copyright (c) 2026 Lark Technologies Pte. Ltd.
// SPDX-License-Identifier: MIT

package plugin_e2e

import (
	"context"
	"os"
	"os/exec"
	"strings"
	"testing"
	"time"

	"github.com/tidwall/gjson"
)

// runIsolated runs bin like run() (harness.go), but with a per-call
// LARKSUITE_CLI_CONFIG_DIR (t.TempDir()) and LARKSUITE_CLI_REMOTE_META=off.
// This is needed ONLY by TestDegradeStubMetadataSchema below: without it, the
// fork inherits this developer machine's real ~/.lark-cli cache (a prior
// `lark-cli` invocation on this box already populated remote_meta.json) and/or
// makes a live network fetch, either of which would populate the runtime
// catalog with real data and hide the #1764 stub-metadata degrade path this
// test exists to pin. harness.go's run() has no env-override parameter and
// must not be modified to add one (out of scope for this task), so this is a
// small local variant of the same subprocess-capture logic.
func runIsolated(t *testing.T, bin string, args ...string) result {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	c := exec.CommandContext(ctx, bin, args...)
	c.Env = append(os.Environ(),
		"LARKSUITE_CLI_NO_UPDATE_NOTIFIER=1",
		"LARKSUITE_CLI_NO_SKILLS_NOTIFIER=1",
		"LARKSUITE_CLI_CONFIG_DIR="+t.TempDir(),
		"LARKSUITE_CLI_REMOTE_META=off",
	)
	var stdout, stderr strings.Builder
	c.Stdout = &stdout
	c.Stderr = &stderr
	err := c.Run()
	exit := 0
	if err != nil {
		if ee, ok := err.(*exec.ExitError); ok {
			exit = ee.ExitCode()
		} else {
			t.Fatalf("run %v: %v", args, err)
		}
	}
	return result{stdout: stdout.String(), stderr: stderr.String(), exit: exit}
}

// plainPlugin registers a minimal observer-only plugin with NO Restrict rule
// -- unlike readonly_test.go's plugins, it cannot deny "schema" as
// out-of-domain, so any failure the command produces below is the command's
// own behavior against the empty stub catalog, not a policy denial.
const plainPlugin = `// Code generated by plugin_e2e; DO NOT EDIT.
package plugin

import (
	"context"

	"github.com/larksuite/cli/extension/platform"
)

func init() {
	platform.Register(
		platform.NewPlugin("plain", "0.1.0").
			Observer(platform.After, "noop", platform.All(),
				func(_ context.Context, _ platform.Invocation) {}).
			FailOpen().
			MustBuild())
}
`

// TestDegradeStubMetadataSchema pins the #1764 stub-metadata degrade path.
// The clean tree embeds only the empty meta_data_default.json stub
// (internal/registry/catalog.go's SchemaCatalog falls through to
// RuntimeCatalog when EmbeddedServicesTyped() is empty), and runIsolated
// additionally disables the remote overlay fetch and points the cache dir at
// an empty tmp dir, so cmd/schema/schema.go's runSchema sees
// catalog.Services() == 0 unconditionally -- the exact "offline with a cold
// cache, remote meta off" branch documented at cmd/schema/schema.go:96-101.
//
// Observed real output for both `schema` and `schema im.messages.reply`
// (identical -- runSchema checks catalog.Services()==0 before parsing args):
//
//	exit=2
//	stdout=(empty)
//	stderr={"ok":false,"error":{"type":"validation","subtype":"failed_precondition",
//	  "message":"No API metadata available",
//	  "hint":"this binary has no embedded API metadata; run any command with
//	  network access to the open platform once so metadata can be fetched and
//	  cached"}}
//
// This is the PINNED "graceful degrade" criterion: a structured JSON envelope
// (gjson.Valid, no "panic:" substring) carrying a validation/failed_precondition
// error with an actionable hint, NOT the raw Go panic crash that
// install_test.go's TestInstallMustBuildInitPanicCrashesBinary pins for a
// genuinely broken plugin, and NOT an "Unknown"-shaped internal error.
// Note: exit==2 alone does not prove "not a crash" -- a genuine Go panic also
// exits 2. The two real discriminators against a crash are the absence of a
// "panic:" substring in stderr and stderr being valid JSON (gjson.Valid); both
// are asserted below.
func TestDegradeStubMetadataSchema(t *testing.T) {
	bin := buildFork(t, "plain", plainPlugin)
	cases := []struct {
		name string
		args []string
	}{
		{"schema root", []string{"schema"}},
		{"schema with path", []string{"schema", "im.messages.reply"}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			res := runIsolated(t, bin, tc.args...)
			t.Logf("exit=%d stdout=%s stderr=%s", res.exit, res.stdout, res.stderr)
			if res.exit != 2 {
				t.Fatalf("exit=%d want 2 (graceful validation exit); stdout=%s stderr=%s", res.exit, res.stdout, res.stderr)
			}
			if strings.Contains(res.stderr, "panic:") {
				t.Fatalf("stderr contains a raw Go panic trace, not a graceful degrade; stderr=%s", res.stderr)
			}
			if !gjson.Valid(res.stderr) {
				t.Fatalf("stderr not a structured JSON envelope: %s", res.stderr)
			}
			if got := gjson.Get(res.stderr, "error.type").String(); got != "validation" {
				t.Errorf("error.type=%q want validation", got)
			}
			if got := gjson.Get(res.stderr, "error.subtype").String(); got != "failed_precondition" {
				t.Errorf("error.subtype=%q want failed_precondition", got)
			}
			if msg := gjson.Get(res.stderr, "error.message").String(); msg != "No API metadata available" {
				t.Errorf("error.message=%q want %q", msg, "No API metadata available")
			}
			if hint := gjson.Get(res.stderr, "error.hint").String(); !strings.Contains(hint, "no embedded API metadata") {
				t.Errorf("error.hint=%q want to contain %q", hint, "no embedded API metadata")
			}
		})
	}
}

// transportAbortPlugin registers a transport.Provider whose Interceptor
// implements AbortableInterceptor and unconditionally rejects every request
// from PreRoundTripE, before the built-in RoundTripper chain (and therefore
// before any real network I/O) ever runs -- see extension/transport/types.go's
// AbortableInterceptor doc and internal/cmdutil/transport.go's RoundTrip.
const transportAbortPlugin = `// Code generated by plugin_e2e; DO NOT EDIT.
package plugin

import (
	"context"
	"errors"
	"net/http"

	"github.com/larksuite/cli/extension/transport"
)

type abortInterceptor struct{}

func (abortInterceptor) PreRoundTrip(req *http.Request) func(*http.Response, error) { return nil }

func (abortInterceptor) PreRoundTripE(req *http.Request) (func(*http.Response, error), error) {
	return nil, errors.New("aborted for test")
}

type abortProvider struct{}

func (abortProvider) Name() string { return "abort-transport" }
func (abortProvider) ResolveInterceptor(ctx context.Context) transport.Interceptor {
	return abortInterceptor{}
}

func init() {
	transport.Register(abortProvider{})
}
`

// TestSubsystemTransportAbort pins the transport.AbortableInterceptor offline
// effect: registering a Provider whose PreRoundTripE always errors turns
// every outbound API call into an abort before any network round trip. The
// destination URL embedded in the message varies run-to-run (it depends on
// whether the SDK fetches an OAuth token first or calls the target endpoint
// first), so the assertion is pinned to the stable part only. Observed real
// output for `docs +fetch --doc nonexistent` (a real read-risk network
// command, run twice across separate `go test -count` invocations):
//
//	run 1: exit=4 stderr={"ok":false,"identity":"user","error":{"type":"network",
//	  "subtype":"transport","message":"API call failed: Post
//	  \"https://open.feishu.cn/open-apis/authen/v2/oauth/token\": extension
//	  \"abort-transport\" aborted round trip: aborted for test"}}
//	run 2: exit=4 stderr={... same shape, message targets
//	  ".../open-apis/docs_ai/v1/documents/nonexistent/fetch" instead ...}
func TestSubsystemTransportAbort(t *testing.T) {
	bin := buildFork(t, "transport-abort", transportAbortPlugin)
	res := run(t, bin, "docs", "+fetch", "--doc", "nonexistent")
	t.Logf("exit=%d stdout=%s stderr=%s", res.exit, res.stdout, res.stderr)
	if res.exit != 4 {
		t.Fatalf("exit=%d want 4; stdout=%s stderr=%s", res.exit, res.stdout, res.stderr)
	}
	if !gjson.Valid(res.stderr) {
		t.Fatalf("stderr not JSON: %s", res.stderr)
	}
	if got := gjson.Get(res.stderr, "error.type").String(); got != "network" {
		t.Errorf("error.type=%q want network", got)
	}
	if got := gjson.Get(res.stderr, "error.subtype").String(); got != "transport" {
		t.Errorf("error.subtype=%q want transport", got)
	}
	if msg := gjson.Get(res.stderr, "error.message").String(); !strings.Contains(msg, `extension "abort-transport" aborted round trip: aborted for test`) {
		t.Errorf("error.message=%q want to contain the abort-transport reason", msg)
	}
}

// credentialBlockPlugin registers a credential.Provider whose ResolveAccount
// (and ResolveToken) unconditionally return a *credential.BlockError.
// internal/credential/credential_provider.go's doResolveAccount returns this
// error straight from the provider loop -- before any defaultAcct fallback
// and, transitively, before the LarkClient/HttpClient phases that would issue
// a real network call ever run (see internal/cmdutil/factory_default.go's
// Phase 2 -> Phase 4 ordering).
const credentialBlockPlugin = `// Code generated by plugin_e2e; DO NOT EDIT.
package plugin

import (
	"context"

	"github.com/larksuite/cli/extension/credential"
)

type blockProvider struct{}

func (blockProvider) Name() string { return "block-cred" }

func (blockProvider) ResolveAccount(ctx context.Context) (*credential.Account, error) {
	return nil, &credential.BlockError{Provider: "block-cred", Reason: "blocked for test"}
}

func (blockProvider) ResolveToken(ctx context.Context, req credential.TokenSpec) (*credential.Token, error) {
	return nil, &credential.BlockError{Provider: "block-cred", Reason: "blocked for test"}
}

func init() {
	credential.Register(blockProvider{})
}
`

// TestSubsystemCredentialBlock pins the credential.BlockError offline effect.
// Observed real output for `docs +fetch --doc nonexistent`, run twice across
// separate `go test -count` invocations (byte-identical both times, unlike
// the transport-abort case -- credential resolution happens once, before any
// endpoint is chosen, so there is no varying destination URL to leak into the
// message):
//
//	exit=5
//	stdout=(empty)
//	stderr={"ok":false,"identity":"bot","error":{"type":"internal","subtype":"unknown",
//	  "message":"blocked by block-cred: blocked for test"}}
func TestSubsystemCredentialBlock(t *testing.T) {
	bin := buildFork(t, "credential-block", credentialBlockPlugin)
	res := run(t, bin, "docs", "+fetch", "--doc", "nonexistent")
	t.Logf("exit=%d stdout=%s stderr=%s", res.exit, res.stdout, res.stderr)
	if res.exit != 5 {
		t.Fatalf("exit=%d want 5; stdout=%s stderr=%s", res.exit, res.stdout, res.stderr)
	}
	if !gjson.Valid(res.stderr) {
		t.Fatalf("stderr not JSON: %s", res.stderr)
	}
	if got := gjson.Get(res.stderr, "error.type").String(); got != "internal" {
		t.Errorf("error.type=%q want internal", got)
	}
	if got := gjson.Get(res.stderr, "error.subtype").String(); got != "unknown" {
		t.Errorf("error.subtype=%q want unknown", got)
	}
	if msg := gjson.Get(res.stderr, "error.message").String(); msg != "blocked by block-cred: blocked for test" {
		t.Errorf("error.message=%q want %q", msg, "blocked by block-cred: blocked for test")
	}
}
