// Copyright (c) 2026 Lark Technologies Pte. Ltd.
// SPDX-License-Identifier: MIT

// Package plugin_e2e exercises the extension/platform plugin contract the way a
// real customer does: it builds a fork of lark-cli with a plugin blank-imported,
// then runs that fork as a subprocess and asserts the real stderr/stdout
// envelopes and exit codes. This is L4 coverage — the in-process unit and
// integration tests (extension/..., cmd/...) assert Go error values in the test
// process and structurally cannot observe envelope serialization, exit codes, or
// the blank-import -> init -> Register -> InstallAll assembly chain.
//
// Mechanism (the "customer build", mirrors xcaddy's build mode):
//  1. `git archive HEAD` a clean tree containing only committed files (so the
//     fork embeds the tracked meta_data stub, reproducing the bare-module state).
//  2. Generate a customer module: go.mod (cli's requires + `replace` to the
//     archived tree) + go.sum copy + main.go (blank-imports the plugin package)
//     + plugin package (its init() calls platform.Register).
//  3. `go build` the fork (offline-capable via the warm module cache), then run
//     it as a subprocess and assert.
package plugin_e2e

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// cleanTree is the git-archived, committed-only source tree of the repo under
// test, shared by every fork build. Populated by TestMain (smoke_test.go) —
// TestMain must live in a _test.go file to be recognized by `go test`, so the
// entry point sits there while the rest of the harness mechanism lives here.
var cleanTree string

// baseDir holds the archive tree plus every generated customer module.
var baseDir string

// repoRoot resolves the lark-cli module root from the test's working directory
// (which `go test` sets to the package dir, tests/plugin_e2e).
func repoRoot() (string, error) {
	out, err := exec.Command("git", "rev-parse", "--show-toplevel").Output()
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(out)), nil
}

// gitArchive extracts HEAD's committed tree into dst. Only tracked files are
// included — gitignored build artifacts (e.g. the fetched meta_data.json) are
// absent, exactly as a module consumer would see them.
func gitArchive(root, dst string) error {
	c := exec.Command("bash", "-c", "git archive HEAD | tar -x -C "+shellQuote(dst))
	c.Dir = root
	return runCmd(c)
}

func shellQuote(s string) string { return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'" }

// builtForks caches fork binaries by name so identical forks are built once.
var builtForks = map[string]string{}

// buildFork generates a customer module whose plugin package body is pluginSrc,
// builds the fork, and returns the binary path. Forks are cached by name.
func buildFork(t *testing.T, name, pluginSrc string) string {
	t.Helper()
	if bin, ok := builtForks[name]; ok {
		return bin
	}
	mod := filepath.Join(baseDir, "fork-"+name)
	if err := os.MkdirAll(filepath.Join(mod, "plugin"), 0o755); err != nil {
		t.Fatalf("mkdir customer module: %v", err)
	}

	// go.mod: reuse cli's require graph, rename the module, replace cli with the
	// local archived tree. This avoids `go mod tidy` (no network at test time).
	rawMod, err := os.ReadFile(filepath.Join(cleanTree, "go.mod"))
	if err != nil {
		t.Fatalf("read archived go.mod: %v", err)
	}
	gomod := strings.Replace(string(rawMod), "module github.com/larksuite/cli", "module larkcustomer", 1)
	gomod += "\nrequire github.com/larksuite/cli v0.0.0\n\nreplace github.com/larksuite/cli => " + cleanTree + "\n"
	writeFile(t, filepath.Join(mod, "go.mod"), gomod)

	// go.sum: transitive dependency hashes are identical to cli's.
	rawSum, err := os.ReadFile(filepath.Join(cleanTree, "go.sum"))
	if err != nil {
		t.Fatalf("read archived go.sum: %v", err)
	}
	writeFile(t, filepath.Join(mod, "go.sum"), string(rawSum))

	writeFile(t, filepath.Join(mod, "main.go"), customerMain)
	writeFile(t, filepath.Join(mod, "plugin", "plugin.go"), pluginSrc)

	bin := filepath.Join(mod, "fork-bin")
	build := exec.Command("go", "build", "-o", bin, ".")
	build.Dir = mod
	// -mod=mod fixes require annotations copied from cli's go.mod; the default
	// GOPROXY resolves any dep missing from the cache (goproxy in CI/dev).
	build.Env = append(os.Environ(), "GOFLAGS=-mod=mod")
	if out, err := build.CombinedOutput(); err != nil {
		t.Fatalf("build fork %q failed: %v\n%s", name, err, out)
	}
	builtForks[name] = bin
	return bin
}

const customerMain = `// Code generated by plugin_e2e; DO NOT EDIT.
package main

import (
	"os"

	"github.com/larksuite/cli/cmd"
	_ "larkcustomer/plugin" // blank import triggers plugin init() -> platform.Register
)

func main() { os.Exit(cmd.Execute()) }
`

// result is a subprocess run outcome.
type result struct {
	stdout string
	stderr string
	exit   int
}

// run executes the fork binary with args and captures stdout/stderr/exit.
// Notifier env vars are suppressed to keep envelopes clean.
func run(t *testing.T, bin string, args ...string) result {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	c := exec.CommandContext(ctx, bin, args...)
	c.Env = append(os.Environ(),
		"LARKSUITE_CLI_NO_UPDATE_NOTIFIER=1",
		"LARKSUITE_CLI_NO_SKILLS_NOTIFIER=1",
	)
	var stdout, stderr strings.Builder
	c.Stdout = &stdout
	c.Stderr = &stderr
	err := c.Run()
	exit := 0
	if err != nil {
		if ee, ok := err.(*exec.ExitError); ok {
			exit = ee.ExitCode()
		} else {
			t.Fatalf("run %v: %v", args, err)
		}
	}
	return result{stdout: stdout.String(), stderr: stderr.String(), exit: exit}
}

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func runCmd(c *exec.Cmd) error {
	if out, err := c.CombinedOutput(); err != nil {
		return &cmdError{err: err, out: out}
	}
	return nil
}

type cmdError struct {
	err error
	out []byte
}

func (e *cmdError) Error() string { return e.err.Error() + ": " + string(e.out) }
