// Copyright (c) 2026 Lark Technologies Pte. Ltd.
// SPDX-License-Identifier: MIT

package plugin_e2e

import (
	"strings"
	"testing"

	"github.com/tidwall/gjson"
)

// readonlyPlugin registers a Restrict rule that only allows read-risk
// commands under the docs/** and im/** domains. It mirrors the official
// example readonly-policy configuration.
const readonlyPlugin = `// Code generated by plugin_e2e; DO NOT EDIT.
package plugin

import "github.com/larksuite/cli/extension/platform"

func init() {
	platform.Register(
		platform.NewPlugin("readonly", "0.1.0").
			Restrict(&platform.Rule{
				Name:    "agent-readonly",
				Allow:   []string{"docs/**", "im/**"},
				MaxRisk: platform.RiskRead,
			}).
			MustBuild())
}
`

// TestReadonlyDenial asserts the VERIFIED denial envelope shape: stderr is
// valid JSON, error.type=="validation", error.subtype=="failed_precondition",
// error.hint contains the literal "reason_code <X>" substring, and the
// process exits 2. reason_code lives only in the hint string, not a
// structured field.
func TestReadonlyDenial(t *testing.T) {
	bin := buildFork(t, "readonly", readonlyPlugin)
	cases := []struct {
		name       string
		args       []string
		reasonCode string
	}{
		{"write in allowed domain", []string{"docs", "+update", "--doc-token", "x", "--content", "y"}, "write_not_allowed"},
		{"leaf out of allow list", []string{"schema"}, "domain_not_allowed"},
		{"parent group all children denied", []string{"sheets"}, "mixed_children_policy"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			res := run(t, bin, tc.args...)
			if res.exit != 2 {
				t.Fatalf("exit=%d stdout=%s stderr=%s", res.exit, res.stdout, res.stderr)
			}
			if !gjson.Valid(res.stderr) {
				t.Fatalf("stderr not JSON: %s", res.stderr)
			}
			if got := gjson.Get(res.stderr, "error.type").String(); got != "validation" {
				t.Errorf("error.type=%q want validation", got)
			}
			if got := gjson.Get(res.stderr, "error.subtype").String(); got != "failed_precondition" {
				t.Errorf("error.subtype=%q want failed_precondition", got)
			}
			if hint := gjson.Get(res.stderr, "error.hint").String(); !strings.Contains(hint, "reason_code "+tc.reasonCode) {
				t.Errorf("hint=%q want to contain reason_code %s", hint, tc.reasonCode)
			}
		})
	}
}

// TestReadonlyAllows asserts the allow-path: a read command inside an
// allowed domain must NOT be denied by the policy gate. It may still fail
// downstream (e.g. api/auth error), but that failure must not carry the
// denial envelope shape and must not exit 2.
func TestReadonlyAllows(t *testing.T) {
	bin := buildFork(t, "readonly", readonlyPlugin)
	res := run(t, bin, "docs", "+fetch", "--doc", "nonexistent")
	if res.exit == 2 {
		t.Fatalf("read command was denied (exit=2); stderr=%s", res.stderr)
	}
	if gjson.Get(res.stderr, "error.subtype").String() == "failed_precondition" {
		t.Errorf("read command produced a denial envelope; stderr=%s", res.stderr)
	}
}
